### ISSUE TITLE
Feature: Submit a poll response

### ISSUE THREAD

**Issue by Marchopkins96** [Marchopkins96/My-First-Agile-Project#4]
In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

## Acceptance Criteria:

The option should be provided as a checkbox.
The checkbox should be checked by default.
The option should appear next to the submit button.
After submitting the default submission confirmation should be adjusted to include username.

## Tasks

- [ ] Update the view: The poll design (HTML & CSS) to include the checkbox and name of the submitter.
- [ ] Create a new field in the model to track the username.
- [ ] Update the controller function.
